version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: calculator-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calculator
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
